import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ky' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ky: {
    'nav.home': 'Башкы бет',
    'nav.newspaper': 'Кыргыз тили гезити',
    'nav.learning': 'Окуу борбору',
    'nav.media': 'Медиа',
    'nav.podcast': 'Подкаст',
    'nav.survey': 'Сурамжылоо (Видео)',
    'nav.news': 'Жаңылыктар',
    'nav.policy': 'Тил саясаты',
    'nav.partners': 'Өнөктөштөр',
    'nav.about': 'Биз жөнүндө',
    'nav.contact': 'Байланыш',
    'header.portal': 'кыргыз тили порталы',
    'header.site_name': 'Кыргыз тил',

    'footer.description': 'Кыргыз тили веб-порталы. Эне тилим - элдүүлүгүм, тил тагдыры - эл тагдыры.',
    'footer.sections': 'Бөлүмдөр',
    'footer.contact': 'Байланыш',
    'footer.address': 'Дареги:',
    'footer.address_value': 'Бишкек ш., Чүй проспекти 265 а',
    'footer.copyright': '© 2026 Kyrgyztil.kg. Бардык укуктар корголгон.',
    'footer.security': 'Коопсуздук',

    'hero.slogan': 'Ураан',
    'hero.news_btn': 'Жаңылыктар',
    'hero.learning_btn': 'Окуу борбору',

    'sub.title': '«Кыргыз тили» гезитине жазылуу',
    'sub.desc': 'Гезиттин жаңы сандарынан кабардар болуп туруу жана PDF версияларын электрондук почтаңызга алуу үчүн жазылыңыз.',
    'sub.safe': 'Маалыматтар коопсуз сакталат',
    'sub.email_label': 'Сиздин e-mail',
    'sub.btn': 'Жазылуу',

    'about.hero.title': 'Биз жөнүндө',
    'about.hero.subtitle': 'Веб-порталдын миссиясы, максаттары жана ишмердүүлүк багыттары',
    'about.mission.title': 'Биздин миссия',
    'about.mission.text1': 'Кыргыз тилин санариптештирүү жана аны жаштарга заманбап форматта жеткирүү.',
    'about.mission.text2': 'Портал кыргыз тилин үйрөнүү, жайылтуу жана коомдук талкууга чыгаруу үчүн бирдиктүү маалыматтык аянтча катары түзүлдү.',
    'about.mission.edu.title': 'Билим берүү',
    'about.mission.edu.desc': 'Тил үйрөнүү ресурстарын санарип форматка өткөрүү.',
    'about.mission.community.title': 'Коомчулук',
    'about.mission.community.desc': 'Кыргыз тилдүү медиа чөйрөнү колдоо жана жайылтуу.',
    'about.activities.title': 'Ишмердүүлүк багыттары',
    'about.activities.1': 'Илимий изилдөөлөр',
    'about.activities.2': 'Санариптик долбоорлор',
    'about.activities.3': 'Окутуу-методикалык иштер',
    'about.activities.4': 'Коомдук иш-чаралар',

    'learning.hero.desc': 'Мамлекеттик тилди заманбап технологиялар менен үйрөнүүгө багытталган материалдар',
    'learning.lessons.title': 'Сабактар',
    'learning.lessons.text.title': 'Текст',
    'learning.lessons.text.desc': 'Макалалар, адабий тексттер жана грамматикалык түшүндүрмөлөр топтому.',
    'learning.lessons.video.title': 'Видео',
    'learning.lessons.video.desc': 'Грамматика, сүйлөө маданияты жана орфография боюнча видео сабактар.',
    'learning.lessons.test.title': 'Тест',
    'learning.lessons.test.desc': 'Тилди билүү деңгээлин аныктоочу суроолор жана практикалык тапшырмалар.',
    'learning.lessons.go': 'Өтүү',
    'learning.methods.title': 'Методикалык материалдар',
    'learning.methods.subtitle': 'Окутуучулар жана изилдөөчүлөр үчүн',
    'learning.methods.desc': 'Бул бөлүмдө кыргыз тилин окутуунун заманбап усулдары, окуу пландары жана методикалык сунуштар топтолгон.',
    'learning.methods.download': 'Жүктөп алуу (.ZIP)',
    'learning.methods.item': 'Методика №',

    'newspaper.subtitle': 'Республикалык коомдук-саясий басылма',
    'newspaper.archive.title': 'Гезит сандары',
    'newspaper.archive.years': 'Архив: 1991-2026',
    'newspaper.sidebar.articles': 'Макалалар',
    'newspaper.sidebar.sub.title': 'Гезитке жазылуу',
    'newspaper.sidebar.sub.desc': 'Гезиттин басылма версиясын почта аркылуу алуу үчүн индекс:',
    'newspaper.sidebar.sub.btn': 'Кененирээк',
    'newspaper.articles.editor': 'Редактордон сөз',
    'newspaper.articles.main': 'Негизги макалалар',
    'newspaper.articles.master': 'Мастер',
    'newspaper.articles.term': 'Терминология',
    'newspaper.articles.culture': 'Тил маданияты',

    'policy.hero.subtitle': 'Мамлекеттик тилди өнүктүрүү стратегиясы',
    'policy.main.title': 'Негизги багыттар',
    'policy.main.desc': 'Тил саясатынын максаты - кыргыз тилинин бардык чөйрөдө толук кандуу колдонулушун камсыз кылуу.',
    'policy.ads.title': 'Көрнөк-жарнактар',
    'policy.ads.desc': 'Көрнөк-жарнактардагы жазуулардын мамлекеттик тил нормаларына шайкештигин текшерүү жана методикалык жардам берүү.',
    'policy.laws.title': 'Мыйзамдык негиздер',
    'policy.laws.desc': 'Мамлекеттик тил жөнүндөгү мыйзамдар, токтомдор жана программалар боюнча маалыматтар.',
    'policy.laws.btn': 'Мыйзамдарды кароо',
    'policy.laws.prog': 'Программалар (PDF)',
    'policy.methods.title': 'Методикалык сунуштар',
    'policy.methods.desc': 'Көрнөк-жарнагыңызды текшерүү же тил каталарын билдирүү үчүн сунуш жөнөтүңүз.',
    'policy.methods.btn': 'Сунуш жөнөтүү',

    'common.search_results': 'Издөөнүн жыйынтыктары',
    'common.search_for': 'Суроо боюнча',
    'common.results_found': 'жыйынтык табылды',
    'common.no_results': 'Эч нерсе табылган жок',
    'common.no_results_desc': 'Сураныч, башка сөздөр менен издөөгө аракет кылып көрүңүз же каталарды текшериңиз.',
    'common.go_home': 'Башкы бетке кайтуу',
    'common.search_placeholder': 'Издөө...',
    'common.find': 'Табуу',
    'common.loading': 'Баракча жүктөлүп жатат',

    'common.read': 'Окуу',
    'common.view': 'Көрүү',
    'common.listen': 'Угуу',
    'common.all': 'Баарын көрүү',
    'common.back': 'Артка кайтуу',
    'common.podcast_episode': 'Подкаст эпизоду',
    'common.video_survey': 'Видео сурамжылоо',
    'common.guest': 'Конок:',
    'common.public_opinion': 'Коомдук пикир',
    'common.playing_now': 'Азыр ойнотулууда',
    'common.info': 'Маалымат',
    'common.other_episodes': 'Башка эпизоддор',
    'common.other_surveys': 'Башка сурамжылоолор',
    'common.main_question': 'Негизги суроо:',
    'common.description': 'Кыскача сүрөттөмө:',
    'common.important_quotes': 'Маанилүү цитаталар:',
    'common.respondent': 'Респондент №',
    'common.more_news': 'Окшош материалдар',
    'common.share': 'Бөлүшүү:',
    'common.send_suggestion': 'Сунуш жөнөтүү',

    'news.desc': 'Тил чөйрөсүндөгү акыркы окуялар',
    'news.all': 'Бардыгы',
    'news.full': 'Толук окуу',

    'media.hero.subtitle': 'Мультимедиа борбору',
    'media.podcast.title': 'Подкаст',
    'media.podcast.desc': 'Маектер, эксперттик пикирлер жана аудио форматтагы окуу материалдары.',
    'media.podcast.hero.title': 'Акыркы эпизоддор',
    'media.podcast.hero.desc': 'Кыргыз тили, тарыхы жана маданияты боюнча маектер',
    'media.survey.title': 'Сурамжылоо (Видео)',
    'media.survey.desc': 'Коомдук пикир, маанилүү суроолор жана видео репортаждар.',
    'media.survey.hero.title': 'Акыркы видеолор',
    'media.survey.hero.desc': 'Коомдук пикирлер жана видео материалдар',
    'media.btn.go': 'Бөлүмгө өтүү',
    'media.topics.all': 'Бардыгы',
    'media.topics.tech': 'Тил жана санарип',
    'media.topics.history': 'Тарых',
    'media.topics.culture': 'Маданият',
    'media.topics.education': 'Билим',

    'partners.hero.subtitle': 'Биздин ишенимдүү өнөктөштөрүбүз',
    'partners.item.role.strategic': 'Стратегиялык өнөктөш',
    'partners.item.role.scientific': 'Илимий өнөктөш',
    'partners.item.role.state': 'Мамлекеттик өнөктөш',
    'partners.item.role.international': 'Эл аралык өнөктөш',
    'partners.btn.site': 'Сайтка өтүү',
    'partners.cta.title': 'Биз менен кызматташыңыз',
    'partners.cta.desc': 'Кыргыз тилин өнүктүрүү багытында демилгеңиз болсо, биз кызматташууга даярбыз.',
    'partners.cta.btn': 'Өнөктөш болуу',

    'contact.subtitle': 'Биз менен байланышыңыз',
    'contact.phone': 'Телефон',
    'contact.email': 'Email',
    'contact.address': 'Дарек',
    'contact.form.title': 'Кайрылуу формасы',
    'contact.form.name': 'Аты-жөнүңүз',
    'contact.form.name_placeholder': 'Атыңыз...',
    'contact.form.email': 'Электрондук почта',
    'contact.form.message': 'Кабарлама',
    'contact.form.message_placeholder': 'Кайрылууңузду жазыңыз...',
    'contact.form.btn': 'Жөнөтүү',

    'home.media.podcast.title': 'Тил жана технология',
    'home.media.podcast.desc': 'Кыргыз тилин санарип доорунда өнүктүрүү боюнча эксперттик маек.',
    'home.media.survey.title': 'Жаштардын тилге болгон көз карашы',

    'cat.events': 'Иш-чаралар',
    'cat.laws': 'Мыйзамдар',
    'cat.projects': 'Долбоорлор',
    'cat.education': 'Окутуу',
    'cat.media_news': 'Медиа жаңылыктар'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.newspaper': 'Газета Кыргыз тили',
    'nav.learning': 'Учебный центр',
    'nav.media': 'Медиа',
    'nav.podcast': 'Подкаст',
    'nav.survey': 'Опрос (Видео)',
    'nav.news': 'Новости',
    'nav.policy': 'Языковая политика',
    'nav.partners': 'Партнеры',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'header.portal': 'портал кыргызского языка',
    'header.site_name': 'Кыргызский язык',

    'footer.description': 'Веб-портал кыргызского языка. Родной язык - наследие народа.',
    'footer.sections': 'Разделы',
    'footer.contact': 'Контакты',
    'footer.address': 'Адрес:',
    'footer.address_value': 'г. Бишкек, проспект Чуй 265 а',
    'footer.copyright': '© 2026 Kyrgyztil.kg. Все права защищены.',
    'footer.security': 'Безопасность',

    'hero.slogan': 'Девиз',
    'hero.news_btn': 'Новости',
    'hero.learning_btn': 'Учебный центр',

    'sub.title': 'Подписка на газету «Кыргыз тили»',
    'sub.desc': 'Подпишитесь, чтобы получать новости о свежих выпусках и PDF-версии газеты.',
    'sub.safe': 'Данные надежно защищены',
    'sub.email_label': 'Ваш e-mail',
    'sub.btn': 'Подписаться',

    'about.hero.title': 'О нас',
    'about.hero.subtitle': 'Миссия, цели и направления деятельности веб-портала',
    'about.mission.title': 'Наша миссия',
    'about.mission.text1': 'Цифровизация кыргызского языка и его продвижение в современном формате.',
    'about.mission.text2': 'Портал создан как единая информационная площадка для изучения, развития и общественного обсуждения кыргызского языка.',
    'about.mission.edu.title': 'Образование',
    'about.mission.edu.desc': 'Перевод учебных ресурсов в цифровой формат.',
    'about.mission.community.title': 'Сообщество',
    'about.mission.community.desc': 'Поддержка и развитие кыргызскоязычной медиа-среды.',
    'about.activities.title': 'Направления деятельности',
    'about.activities.1': 'Научные исследования',
    'about.activities.2': 'Цифровые проекты',
    'about.activities.3': 'Учебно-методическая работа',
    'about.activities.4': 'Общественные мероприятия',

    'learning.hero.desc': 'Материалы для изучения государственного языка с использованием современных технологий',
    'learning.lessons.title': 'Уроки',
    'learning.lessons.text.title': 'Текст',
    'learning.lessons.text.desc': 'Статьи, художественные тексты и грамматические объяснения.',
    'learning.lessons.video.title': 'Видео',
    'learning.lessons.video.desc': 'Видеоуроки по грамматике, культуре речи и орфографии.',
    'learning.lessons.test.title': 'Тест',
    'learning.lessons.test.desc': 'Вопросы и практические задания для проверки уровня владения языком.',
    'learning.lessons.go': 'Перейти',
    'learning.methods.title': 'Методические материалы',
    'learning.methods.subtitle': 'Для преподавателей и исследователей',
    'learning.methods.desc': 'В разделе собраны современные методы обучения кыргызскому языку, учебные планы и методические рекомендации.',
    'learning.methods.download': 'Скачать (.ZIP)',
    'learning.methods.item': 'Методика №',

    'newspaper.subtitle': 'Республиканское общественно-политическое издание',
    'newspaper.archive.title': 'Выпуски газеты',
    'newspaper.archive.years': 'Архив: 1991-2026',
    'newspaper.sidebar.articles': 'Статьи',
    'newspaper.sidebar.sub.title': 'Подписка на газету',
    'newspaper.sidebar.sub.desc': 'Индекс для получения печатной версии по почте:',
    'newspaper.sidebar.sub.btn': 'Подробнее',
    'newspaper.articles.editor': 'Слово редактора',
    'newspaper.articles.main': 'Основные статьи',
    'newspaper.articles.master': 'Мастер',
    'newspaper.articles.term': 'Терминология',
    'newspaper.articles.culture': 'Культура языка',

    'policy.hero.subtitle': 'Стратегия развития государственного языка',
    'policy.main.title': 'Основные направления',
    'policy.main.desc': 'Цель языковой политики - обеспечить полноценное использование кыргызского языка во всех сферах.',
    'policy.ads.title': 'Вывески и реклама',
    'policy.ads.desc': 'Проверка соответствия вывесок и рекламных текстов нормам государственного языка и методическая поддержка.',
    'policy.laws.title': 'Законодательная база',
    'policy.laws.desc': 'Информация о законах, постановлениях и программах по государственному языку.',
    'policy.laws.btn': 'Смотреть законы',
    'policy.laws.prog': 'Программы (PDF)',
    'policy.methods.title': 'Методические рекомендации',
    'policy.methods.desc': 'Отправьте предложение, если хотите проверить вывеску или сообщить об ошибке в тексте.',
    'policy.methods.btn': 'Отправить предложение',

    'common.search_results': 'Результаты поиска',
    'common.search_for': 'По запросу',
    'common.results_found': 'результатов найдено',
    'common.no_results': 'Ничего не найдено',
    'common.no_results_desc': 'Пожалуйста, попробуйте поискать по другим словам или проверьте ошибки.',
    'common.go_home': 'Вернуться на главную',
    'common.search_placeholder': 'Поиск...',
    'common.find': 'Найти',
    'common.loading': 'Страница загружается',

    'common.read': 'Читать',
    'common.view': 'Смотреть',
    'common.listen': 'Слушать',
    'common.all': 'Смотреть все',
    'common.back': 'Назад',
    'common.podcast_episode': 'Эпизод подкаста',
    'common.video_survey': 'Видео опрос',
    'common.guest': 'Гость:',
    'common.public_opinion': 'Общественное мнение',
    'common.playing_now': 'Сейчас играет',
    'common.info': 'Информация',
    'common.other_episodes': 'Другие эпизоды',
    'common.other_surveys': 'Другие опросы',
    'common.main_question': 'Главный вопрос:',
    'common.description': 'Краткое описание:',
    'common.important_quotes': 'Важные цитаты:',
    'common.respondent': 'Респондент №',
    'common.more_news': 'Похожие материалы',
    'common.share': 'Поделиться:',
    'common.send_suggestion': 'Отправить предложение',

    'news.desc': 'Последние события в языковой сфере',
    'news.all': 'Все',
    'news.full': 'Читать полностью',

    'media.hero.subtitle': 'Мультимедиа центр',
    'media.podcast.title': 'Подкаст',
    'media.podcast.desc': 'Интервью, экспертные мнения и учебные материалы в аудиоформате.',
    'media.podcast.hero.title': 'Последние эпизоды',
    'media.podcast.hero.desc': 'Беседы о кыргызском языке, истории и культуре',
    'media.survey.title': 'Опрос (Видео)',
    'media.survey.desc': 'Общественное мнение, важные вопросы и видеорепортажи.',
    'media.survey.hero.title': 'Последние видео',
    'media.survey.hero.desc': 'Общественные мнения и видеоматериалы',
    'media.btn.go': 'Перейти в раздел',
    'media.topics.all': 'Все',
    'media.topics.tech': 'Язык и цифра',
    'media.topics.history': 'История',
    'media.topics.culture': 'Культура',
    'media.topics.education': 'Образование',

    'partners.hero.subtitle': 'Наши надежные партнеры',
    'partners.item.role.strategic': 'Стратегический партнер',
    'partners.item.role.scientific': 'Научный партнер',
    'partners.item.role.state': 'Государственный партнер',
    'partners.item.role.international': 'Международный партнер',
    'partners.btn.site': 'Перейти на сайт',
    'partners.cta.title': 'Сотрудничайте с нами',
    'partners.cta.desc': 'Если у вас есть инициативы по развитию кыргызского языка, мы готовы к сотрудничеству.',
    'partners.cta.btn': 'Стать партнером',

    'contact.subtitle': 'Свяжитесь с нами',
    'contact.phone': 'Телефон',
    'contact.email': 'Email',
    'contact.address': 'Адрес',
    'contact.form.title': 'Форма обращения',
    'contact.form.name': 'Ваше имя',
    'contact.form.name_placeholder': 'Ваше имя...',
    'contact.form.email': 'Электронная почта',
    'contact.form.message': 'Сообщение',
    'contact.form.message_placeholder': 'Напишите ваше сообщение...',
    'contact.form.btn': 'Отправить',

    'home.media.podcast.title': 'Язык и технологии',
    'home.media.podcast.desc': 'Экспертная беседа о развитии кыргызского языка в цифровую эпоху.',
    'home.media.survey.title': 'Взгляд молодежи на язык',

    'cat.events': 'Мероприятия',
    'cat.laws': 'Законы',
    'cat.projects': 'Проекты',
    'cat.education': 'Обучение',
    'cat.media_news': 'Медиа новости'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ky');

  const t = (key: string) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
